import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
import { CLIENT_LAYERS, renderClient } from '../scripts/build-client.mjs'

test('client.js is the concatenation of src/client layers', async () => {
  const built = await readFile(new URL('../client.js', import.meta.url), 'utf8')
  const expected = await renderClient()
  assert.equal(built, expected)
  assert.match(built, /^\/\/ Generated by scripts\/build-client\.mjs/)
  assert.deepEqual(CLIENT_LAYERS, [
    'constants.js',
    'css/tokens.js',
    'css/sidebar-island.js',
    'css/conversation-pane.js',
    'css/conversation-title.js',
    'css/conversation-scroll.js',
    'css/composer.js',
    'css/overlays.js',
    'css/sidebar-chrome.js',
    'css/cards.js',
    'css/settings.js',
    'css/crop.js',
    'css/a11y.js',
    'css.js',
    'storage.js',
    'i18n.js',
    'wallpaper-state.js',
    'optics-sdf.js',
    'optics-map.js',
    'optics-measure.js',
    'generated-optics-fallbacks.js',
    'controller-styles.js',
    'controller.js',
    'settings-import.js',
    'crop-view.js',
    'settings-view.js',
    'settings.js',
    'runtime-scheduler.js',
    'metal.js',
    'metrics.js',
    'apply.js',
  ])
  assert.ok(CLIENT_LAYERS.indexOf('runtime-scheduler.js') < CLIENT_LAYERS.indexOf('metal.js'))
  assert.ok(CLIENT_LAYERS.indexOf('runtime-scheduler.js') < CLIENT_LAYERS.indexOf('metrics.js'))
  assert.ok(CLIENT_LAYERS.indexOf('optics-map.js') < CLIENT_LAYERS.indexOf('controller-styles.js'))
  assert.equal(CLIENT_LAYERS.at(-1), 'apply.js')
  assert.equal(new Set(CLIENT_LAYERS).size, CLIENT_LAYERS.length)
})
